version: "3.3"

services:
  plutous-jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: plutous-jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SHELL=/bin/bash
    volumes:
      - .:/root/plutous
      - ./notebooks:/root/work
      - ./data:/root/work/data
      - ./secrets:/root/work/secrets
    ports:
      - "8888:8888"
    command: jupyter lab --port=8888 --ip 0.0.0.0 --allow-root --NotebookApp.token=''
    stdin_open: true
    tty: true